### ISSUE TITLE
[3.5.8] Error XHR returned response code 500

### ISSUE THREAD

**Issue by wowmatu** [osclass/Osclass#1947]
Error: XHR returned response code 500

The mistake arose after auto upgrade to 3.5.8

Hello, from today I am having problems uploading pictures at the time of publication ...

I always get that error ...
http://donclasificados.com/publicar

Read More: http://forums.osclass.org/3-5-x/error-xhr-returned-response-code-500/msg131205

**Comment by wowmatu** [comment]
Solved upload AjaxUploader.php (Osclass 3.5.7)

**Comment by dev-101** [comment]
fixed via https://github.com/osclass/Osclass/commit/23f4458110d2258c1f0605c584ceaf0524c87b6e

(issue can be closed)

**Comment by anvarsadiqp** [comment]
Still Have the Same issue

http://forums.osclass.org/themes-26/xhr-returned-response-code-500-please-help-when-uploading-images/msg137634/#msg137634

**Comment by conejoninja** [comment]
The issue is marked as fixed, so specify what issue are yo experiencing, you should be using latest version (at the time of writing this 3.6.1).

Also, provide more information, enable PHP debug : https://doc.osclass.org/Debug_PHP_errors  to see what the error is. No need to post this on multiple sites.

**Comment by fikirzen** [comment]
phone sites when uploading XHR RETUREND RESPONSE CODE 500    :( 
software 3.6.1
www.cayirovailan.com

**Comment by krisztianmark** [comment]
Hello!

enable php imagemagick/imagick
oc-admin/settings / media : Use ImageMagick instead of GD library

**Comment by krisztianmark** [comment]
+  /home/public_html   delete php.ini
